### ISSUE TITLE
Turn on CodeClimate coverage reporting

### ISSUE THREAD

**Issue by mecampbellsoup** [zipmark/profiles-api#1]
* [x] Add CODECLIMATE_REPO_TOKEN as CI env variable
* [ ] turn on reporting in repo

**Comment by jakehow** [comment]
Added project to CC and add env variable

**Comment by mecampbellsoup** [comment]
@jakehow `profiles-api` has the necessary gem/code to send coverage statistics as well: https://github.com/zipmark/profiles-api/blob/224ebefb1f076dc74e8568219bc12cd2bbeab4eb/spec/spec_helper.rb#L18-L19

This is also part of our template so going forward we'll only need to add the CC env variable to CI to wire everything up properly: https://github.com/zipmark/microservice/blob/9619724bd10a57e9af47317eb3cd6cc1de0a6120/lib/microservice/api_template.rb#L111

**Comment by mecampbellsoup** [comment]
I'll close this once I see coverage statistics (after next push I think) in CodeClimate for `profiles-api`.

**Comment by mecampbellsoup** [comment]
@jakehow closing: https://codeclimate.com/repos/5761b27f91d547007d003728/feed
